# Generated by Django 5.2.4 on 2026-08-20 23:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_category_organization_alter_product_barcode_and_more'),
        ('sales', '0003_sale_client_request_id_and_more'),
        ('tenants', '0004_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='saldo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='tenants.organization', verbose_name='organização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.product', verbose_name='produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='tenants.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
                'ordering': ['store__name', 'product__name'],
                'indexes': [models.Index(fields=['organization', 'store'], name='inventory_s_organiz_9af31b_idx'), models.Index(fields=['organization', 'product'], name='inventory_s_organiz_d9027c_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_stock_per_store_product')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inbound', 'Entrada'), ('sale', 'Venda'), ('sale_reversal', 'Estorno de venda'), ('adjustment', 'Ajuste')], max_length=24, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='saldo após movimento')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='tenants.organization', verbose_name='organização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product', verbose_name='produto')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.sale', verbose_name='venda')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='tenants.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'store', 'product', 'created_at'], name='inventory_s_organiz_b01eca_idx'), models.Index(fields=['sale', 'movement_type'], name='inventory_s_sale_id_711abc_idx')],
            },
        ),
    ]
