# Generated by Django 5.2.4 on 2026-07-30 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('tenants', '0003_alter_organization_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tenants.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tenants.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='tenants.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=12, verbose_name='símbolo'),
        ),
        migrations.AlterConstraint(
            model_name='category',
            name='unique_category_name_per_organization',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_name_per_organization', violation_error_message='Já existe uma categoria com este nome nesta organização.'),
        ),
        migrations.AlterConstraint(
            model_name='product',
            name='unique_product_sku_per_organization',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='unique_product_sku_per_organization', violation_error_message='Já existe um produto com este SKU nesta organização.'),
        ),
        migrations.AlterConstraint(
            model_name='unit',
            name='unique_unit_symbol_per_organization',
            constraint=models.UniqueConstraint(fields=('organization', 'symbol'), name='unique_unit_symbol_per_organization', violation_error_message='Já existe uma unidade com este símbolo nesta organização.'),
        ),
    ]
