# Generated by Django 5.2.4 on 2026-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='usuário informado')),
                ('normalized_username', models.CharField(db_index=True, max_length=150, verbose_name='usuário normalizado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('locked', 'Bloqueado')], max_length=16, verbose_name='status')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_username', 'ip_address', 'created_at'], name='accounts_lo_normali_43691b_idx'), models.Index(fields=['status', 'created_at'], name='accounts_lo_status_efc992_idx')],
            },
        ),
    ]
