# Generated by Django 5.2.4 on 2026-08-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='usuário')),
                ('event_type', models.CharField(choices=[('logout', 'Logout'), ('password_change', 'Troca de senha')], max_length=32, verbose_name='tipo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'evento de autenticação',
                'verbose_name_plural': 'eventos de autenticação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='accounts_au_user_id_32a5cb_idx'), models.Index(fields=['event_type', 'created_at'], name='accounts_au_event_t_8b5a9b_idx')],
            },
        ),
    ]
