# Generated by Django 5.2.4 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('logout', 'Logout'), ('password_change', 'Troca de senha'), ('password_reset', 'Redefinição de senha'), ('session_revoked', 'Sessão revogada')], max_length=32, verbose_name='tipo'),
        ),
    ]
