# Generated by Django 5.2.4 on 2026-07-30 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('document', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='tenants_org_is_acti_c2ed40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='tenants.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('operator', 'Operador'), ('cashier', 'Caixa'), ('fiscal', 'Fiscal')], default='operator', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserStoreAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accesses', to='tenants.userprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='tenants.store')),
            ],
            options={
                'ordering': ['profile__user__username', 'store__name'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['organization', 'is_active'], name='tenants_sto_organiz_90fdf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_store_code_per_organization'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='tenants_use_organiz_d35c62_idx'),
        ),
        migrations.AddIndex(
            model_name='userstoreaccess',
            index=models.Index(fields=['store', 'is_active'], name='tenants_use_store_i_99fc8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userstoreaccess',
            constraint=models.UniqueConstraint(fields=('profile', 'store'), name='unique_user_store_access'),
        ),
    ]
