# Generated by Django 5.2.4 on 2026-07-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organizacao', 'verbose_name_plural': 'organizacoes'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['organization__name', 'name'], 'verbose_name': 'loja', 'verbose_name_plural': 'lojas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['organization__name', 'user__username'], 'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfis de usuario'},
        ),
        migrations.AlterModelOptions(
            name='userstoreaccess',
            options={'ordering': ['profile__user__username', 'store__name'], 'verbose_name': 'acesso de usuario a loja', 'verbose_name_plural': 'acessos de usuarios a lojas'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='document',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='razao social'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=160, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=32, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=160, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='store',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='tenants.organization', verbose_name='organizacao'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.organization', verbose_name='organizacao'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('operator', 'Operador'), ('cashier', 'Caixa'), ('fiscal', 'Fiscal')], default='operator', max_length=24, verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='userstoreaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='userstoreaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='userstoreaccess',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accesses', to='tenants.userprofile', verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='userstoreaccess',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='tenants.store', verbose_name='loja'),
        ),
        migrations.AlterConstraint(
            model_name='store',
            name='unique_store_code_per_organization',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_store_code_per_organization', violation_error_message='Ja existe uma loja com este codigo nesta organizacao.'),
        ),
        migrations.AlterConstraint(
            model_name='userstoreaccess',
            name='unique_user_store_access',
            constraint=models.UniqueConstraint(fields=('profile', 'store'), name='unique_user_store_access', violation_error_message='Este usuario ja possui acesso a esta loja.'),
        ),
    ]
