# Generated by Django 5.2.4 on 2026-07-30 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_organization_options_alter_store_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organização', 'verbose_name_plural': 'organizações'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['organization__name', 'user__username'], 'verbose_name': 'perfil de usuário', 'verbose_name_plural': 'perfis de usuário'},
        ),
        migrations.AlterModelOptions(
            name='userstoreaccess',
            options={'ordering': ['profile__user__username', 'store__name'], 'verbose_name': 'acesso de usuário a loja', 'verbose_name_plural': 'acessos de usuários a lojas'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='razão social'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=32, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='store',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='tenants.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='tenants.organization', verbose_name='organização'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterConstraint(
            model_name='store',
            name='unique_store_code_per_organization',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_store_code_per_organization', violation_error_message='Já existe uma loja com este código nesta organização.'),
        ),
        migrations.AlterConstraint(
            model_name='userstoreaccess',
            name='unique_user_store_access',
            constraint=models.UniqueConstraint(fields=('profile', 'store'), name='unique_user_store_access', violation_error_message='Este usuário já possui acesso a esta loja.'),
        ),
    ]
