# Generated by Django 5.2.4 on 2026-08-14 21:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_category_organization_alter_product_barcode_and_more'),
        ('tenants', '0004_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='completed', max_length=24, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenants.organization', verbose_name='organização')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tenants.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='nome do produto')),
                ('product_sku', models.CharField(max_length=64, verbose_name='SKU do produto')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço unitário')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total do item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'item de venda',
                'verbose_name_plural': 'itens de venda',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'store', 'created_at'], name='sales_sale_organiz_b84fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='sales_sale_organiz_239547_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product', 'created_at'], name='sales_salei_product_882dd0_idx'),
        ),
    ]
