# Generated by Django 5.2.4 on 2026-08-14 22:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor recebido'),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='troco'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card_external', 'Cartão externo'), ('pix_manual', 'Pix manual'), ('other', 'Outro')], default='cash', max_length=24, verbose_name='forma de pagamento'),
        ),
    ]
