# Generated by Django 5.2.4 on 2026-08-14 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_amount_received_sale_change_amount_and_more'),
        ('tenants', '0004_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID da requisição do PDV'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('cashier', 'store', 'client_request_id'), name='unique_sale_client_request_per_cashier_store'),
        ),
    ]
