# Generated by Django 5.2.4 on 2026-08-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='sales.salepayment')),
            ],
            options={
                'verbose_name': 'evento de webhook de pagamento',
                'verbose_name_plural': 'eventos de webhook de pagamento',
            },
        ),
    ]
