# Generated by Django 5.2.4 on 2026-09-07 17:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_cardpaymenttransaction'),
        ('tenants', '0005_store_pix_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=12, verbose_name='status')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor de abertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de fechamento')),
                ('closing_note', models.CharField(blank=True, max_length=240, verbose_name='observação do fechamento')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_register_sessions', to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_register_sessions', to=settings.AUTH_USER_MODEL, verbose_name='aberto por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_sessions', to='tenants.organization', verbose_name='organização')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_sessions', to='tenants.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'sessão de caixa',
                'verbose_name_plural': 'sessões de caixa',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashRegisterMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('supply', 'Suprimento'), ('withdrawal', 'Sangria')], max_length=16, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('reason', models.CharField(max_length=240, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='sales.cashregistersession', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'movimentação de caixa',
                'verbose_name_plural': 'movimentações de caixa',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='cashregistersession',
            index=models.Index(fields=['organization', 'store', 'status', 'opened_at'], name='sales_cashr_organiz_74c985_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('store',), name='unique_open_cash_session_per_store'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount__gte', 0)), name='cash_session_opening_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashregistersession',
            constraint=models.CheckConstraint(condition=models.Q(('closing_amount__gte', 0), ('closing_amount__isnull', True), _connector='OR'), name='cash_session_closing_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashregistermovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movement_amount_positive'),
        ),
    ]
