# Generated by Django 5.2.4 on 2026-09-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_cashregistersession_cashregistermovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashregistersession', verbose_name='sessão de caixa'),
        ),
    ]
